[package]
name = "example-asset-manager-basic"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
asset-traits = { path = "../../asset-traits" }
asset-macros = { path = "../../asset-macros" }
